// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVhiA1wsR2CbawhzUw18iUiLRzHlPoLE4',
    appId: '1:163934683202:web:80e5956b19a8ffc506addb',
    messagingSenderId: '163934683202',
    projectId: 'sneaker-shop-flutter',
    authDomain: 'sneaker-shop-flutter.firebaseapp.com',
    storageBucket: 'sneaker-shop-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBieS5mA1vMHmJBIET4DD1jl-F2fem5TkQ',
    appId: '1:163934683202:android:95de1866af30d71b06addb',
    messagingSenderId: '163934683202',
    projectId: 'sneaker-shop-flutter',
    storageBucket: 'sneaker-shop-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdRWqfcBSDFKa57qqfAxfDuu9Weaoeu-w',
    appId: '1:163934683202:ios:34e92fec7d0d6ba406addb',
    messagingSenderId: '163934683202',
    projectId: 'sneaker-shop-flutter',
    storageBucket: 'sneaker-shop-flutter.firebasestorage.app',
    iosBundleId: 'com.example.shopsneaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdRWqfcBSDFKa57qqfAxfDuu9Weaoeu-w',
    appId: '1:163934683202:ios:34e92fec7d0d6ba406addb',
    messagingSenderId: '163934683202',
    projectId: 'sneaker-shop-flutter',
    storageBucket: 'sneaker-shop-flutter.firebasestorage.app',
    iosBundleId: 'com.example.shopsneaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVhiA1wsR2CbawhzUw18iUiLRzHlPoLE4',
    appId: '1:163934683202:web:48364fddb56bc32206addb',
    messagingSenderId: '163934683202',
    projectId: 'sneaker-shop-flutter',
    authDomain: 'sneaker-shop-flutter.firebaseapp.com',
    storageBucket: 'sneaker-shop-flutter.firebasestorage.app',
  );
}
